# -*- coding: utf-8 -*-
"""
크라운 STL 하나를 출력 파일로 (2026-10-06).

덴트버드에서 받은 STL → 방향 맞추기 → 오르카로 자르기 → `.gcode.3mf`
그리고 **돌려 놓은 모습을 그림으로** 남깁니다.

★ 오르카의 회전 옵션은 쓰지 않습니다. 돌리기는 orient.py 가 합니다.
  (2.4.2 에서 --rotate-x 는 세그폴트로 죽습니다 — 실측 2026-10-06)

★ 그림을 꼭 남깁니다 (사용자 원칙 — "1개라도 잘못 들어오면 치명적").
  출력이 끝난 뒤에 방향이 틀린 것을 알면 늦습니다. 사람이 눈으로
  잡을 기회를 한 번은 줘야 합니다.

★ 오르카가 Windows 에서 콘솔에 아무것도 안 뱉습니다 (GUI 실행 파일).
  파일로 받아야 보입니다. 실패하면 그 로그 끝부분을 까닭으로 올립니다.

혼자 돌려 보기:
    python slice_job.py 크라운.stl --out 결과폴더 --rx 150 --ry 140
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import zipfile
from pathlib import Path

from orient import place
from orca_profile import orca_exe
from stl_render import load_stl, render

#: 출력판 크기. 기종이 정해지면 프로파일에서 읽어 옵니다
DEFAULT_BED = (256.0, 256.0)

#: 자르기가 이보다 오래 걸리면 뭔가 잘못된 것입니다
SLICE_TIMEOUT = 180


class SliceError(RuntimeError):
    """자르다 실패. 메시지는 사람이 읽을 한 줄입니다"""


def _tail(log: Path, lines: int = 6) -> str:
    try:
        text = log.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    return " / ".join(t.strip() for t in text.splitlines()[-lines:] if t.strip())


def run_orca(
    stl: Path,
    out_3mf: Path,
    machine: Path,
    process: Path,
    filament: Path,
    log: Path | None = None,
) -> None:
    """
    오르카로 자릅니다. 돌리기는 이미 끝났다고 봅니다.

    ★ 경로는 **절대 경로**여야 합니다. 상대 경로면 "can not find setting file".
    """
    exe = orca_exe()
    if not exe.exists():
        raise SliceError(f"오르카를 찾지 못했습니다: {exe}")

    log = log or out_3mf.with_suffix(".log")
    cmd = [
        str(exe),
        "--debug", "2",
        "--slice", "0",
        "--load-settings", f"{machine.resolve()};{process.resolve()}",
        "--load-filaments", str(filament.resolve()),
        "--export-3mf", str(out_3mf.resolve()),
        str(stl.resolve()),
    ]

    with open(log, "wb") as f:
        try:
            code = subprocess.call(cmd, stdout=f, stderr=f, cwd=str(out_3mf.parent),
                                   timeout=SLICE_TIMEOUT)
        except subprocess.TimeoutExpired:
            raise SliceError("자르기가 너무 오래 걸립니다") from None

    if code != 0 or not out_3mf.exists():
        why = _tail(log) or f"오르카가 {code} 로 끝났습니다"
        raise SliceError(f"자르지 못했습니다 — {why}")


def facts_of(out_3mf: Path) -> dict:
    """
    출력 파일에서 사람이 볼 값을 꺼냅니다.

    ★ `.gcode.3mf` 는 zip 입니다. 안에 `Metadata/plate_1.gcode` 가 있어야
      **진짜 자른 것**입니다. 없으면 프로젝트만 저장된 것이고 프린터가 안 받습니다.
    """
    with zipfile.ZipFile(out_3mf) as z:
        names = z.namelist()
        gcode = next((n for n in names if re.fullmatch(r"Metadata/plate_\d+\.gcode", n)), None)
        if not gcode:
            raise SliceError("출력 파일에 gcode 가 없습니다 (프린터가 받지 않습니다)")

        head = z.read(gcode).decode("utf-8", "replace")[:4000]

    def grab(pattern: str) -> str | None:
        m = re.search(pattern, head)
        return m.group(1).strip() if m else None

    return {
        "bytes": out_3mf.stat().st_size,
        "slicer": grab(r"generated by (OrcaSlicer [\d.]+)"),
        "print_time": grab(r"total estimated time: ([^\n;]+)"),
        "layers": int(grab(r"total layer number: (\d+)") or 0),
    }


def preview(stl: Path, png: Path, size: int = 420) -> Path:
    """
    돌려 놓은 모습 한 장. 비스듬히 봅니다 — 눕힌 각도가 보여야 합니다.
    """
    tris = load_stl(stl)
    render(tris, elev=62, azim=35, size=size).save(png)
    return png


def build(
    stl: Path,
    out_dir: Path,
    machine: Path,
    process: Path,
    filament: Path,
    rx: float = 0.0,
    ry: float = 0.0,
    rz: float = 0.0,
    bed: tuple[float, float] = DEFAULT_BED,
    stem: str | None = None,
) -> dict:
    """
    STL 하나 → 출력 파일 + 그림 + 적어 둘 값.

    돌려주는 것은 그대로 auto_jobs 에 적을 수 있는 모양입니다.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = stem or stl.stem

    rotated = out_dir / f"{stem}_놓임.stl"
    placed = place(stl, rotated, rx=rx, ry=ry, rz=rz, bed=bed)

    out_3mf = out_dir / f"{stem}.gcode.3mf"
    run_orca(rotated, out_3mf, machine, process, filament)

    png = preview(rotated, out_dir / f"{stem}_놓임.png")

    return {
        "stl": str(rotated),
        "print_file": str(out_3mf),
        "preview": str(png),
        **placed,
        **facts_of(out_3mf),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="크라운 STL 을 출력 파일로")
    ap.add_argument("stl", type=Path)
    ap.add_argument("--out", type=Path, default=Path("out"))
    ap.add_argument("--rx", type=float, default=0.0)
    ap.add_argument("--ry", type=float, default=0.0)
    ap.add_argument("--rz", type=float, default=0.0)
    args = ap.parse_args(argv)

    from orca_profile import pick, ready

    if not ready():
        print("오르카를 한 번 켜 주세요 (첫 실행에서 설정이 만들어집니다)", file=sys.stderr)
        return 2

    prof = pick()
    missing = prof.missing()
    if missing:
        print("프로파일이 없습니다: " + ", ".join(p.name for p in missing), file=sys.stderr)
        return 2

    try:
        got = build(args.stl, args.out, *prof.as_tuple(), rx=args.rx, ry=args.ry, rz=args.rz)
    except SliceError as e:
        print(f"실패: {e}", file=sys.stderr)
        return 1

    print(json.dumps(got, ensure_ascii=False, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
